# Generated by Django 6.0.6 on 2026-06-19 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('asset_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('server', 'Server'), ('network', 'Network device'), ('printer', 'Printer'), ('mobile', 'Mobile device'), ('software', 'Software')], default='laptop', max_length=20)),
                ('status', models.CharField(choices=[('in_use', 'In use'), ('in_stock', 'In stock'), ('repair', 'In repair'), ('retired', 'Retired')], default='in_use', max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('purchased_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_tag'],
            },
        ),
    ]
